<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FauloInfection</AssemblyName>
    <RootNamespace>FauloInfection</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Locale\*.xml" />
    <EmbeddedResource Include="modinfo.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Buttons\" />
  </ItemGroup>

  <Import Project="..\AmongUs.props" />
</Project>
